Name:           ros-indigo-map-ray-caster
Version:        0.1.6
Release:        0%{?dist}
Summary:        ROS map_ray_caster package

Group:          Development/Libraries
License:        BSD
URL:            http://wiki.ros.org/map_ray_caster
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-indigo-lama-msgs
Requires:       ros-indigo-nav-msgs
Requires:       ros-indigo-roscpp
BuildRequires:  ros-indigo-catkin
BuildRequires:  ros-indigo-lama-msgs
BuildRequires:  ros-indigo-nav-msgs
BuildRequires:  ros-indigo-roscpp

%description
The map_ray_caster package provides a class for cached ray casting on maps. The
origin of all rays is fixed relative to the map, it is the map center.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Thu Jan 15 2015 Gaël Ecorchard <gael.ecorchard@ciirc.cvut.cz> - 0.1.6-0
- Autogenerated by Bloom

* Wed Jan 14 2015 Gaël Ecorchard <gael.ecorchard@ciirc.cvut.cz> - 0.1.5-0
- Autogenerated by Bloom

* Wed Jan 14 2015 Gaël Ecorchard <gael.ecorchard@ciirc.cvut.cz> - 0.1.2-0
- Autogenerated by Bloom

* Tue Jan 13 2015 Gaël Ecorchard <gael.ecorchard@ciirc.cvut.cz> - 0.1.1-1
- Autogenerated by Bloom

* Mon Jan 12 2015 Gaël Ecorchard <gael.ecorchard@ciirc.cvut.cz> - 0.1.1-0
- Autogenerated by Bloom

