Name:           ros-indigo-goto-crossing
Version:        0.1.5
Release:        0%{?dist}
Summary:        ROS goto_crossing package

Group:          Development/Libraries
License:        BSD
URL:            http://wiki.ros.org/goto_crossing
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-indigo-angles
Requires:       ros-indigo-geometry-msgs
Requires:       ros-indigo-lama-msgs
Requires:       ros-indigo-message-runtime
Requires:       ros-indigo-roscpp
Requires:       ros-indigo-std-msgs
Requires:       ros-indigo-std-srvs
BuildRequires:  ros-indigo-angles
BuildRequires:  ros-indigo-catkin
BuildRequires:  ros-indigo-geometry-msgs
BuildRequires:  ros-indigo-lama-msgs
BuildRequires:  ros-indigo-message-generation
BuildRequires:  ros-indigo-roscpp
BuildRequires:  ros-indigo-std-msgs
BuildRequires:  ros-indigo-std-srvs

%description
The goto_crossing package provides a goToGoal behavior to a crossing center if
the crossing has at least three frontiers and some kind of move forward behavior
if it has two or less frontiers.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Wed Jan 14 2015 Gaël Ecorchard <gael.ecorchard@ciirc.cvut.cz> - 0.1.5-0
- Autogenerated by Bloom

* Wed Jan 14 2015 Gaël Ecorchard <gael.ecorchard@ciirc.cvut.cz> - 0.1.2-0
- Autogenerated by Bloom

* Tue Jan 13 2015 Gaël Ecorchard <gael.ecorchard@ciirc.cvut.cz> - 0.1.1-1
- Autogenerated by Bloom

* Mon Jan 12 2015 Gaël Ecorchard <gael.ecorchard@ciirc.cvut.cz> - 0.1.1-0
- Autogenerated by Bloom

